name: Setup BuildStream CI Environment
description: |
  Shared setup for BuildStream CI jobs: free disk space, checkout,
  pull bst2 image, restore caches (GitHub Actions + R2), generate
  BuildStream CI config. Used by both warmup and assembly jobs.

inputs:
  r2-access-key:
    description: Cloudflare R2 access key ID
    required: false
    default: ''
  r2-secret-key:
    description: Cloudflare R2 secret access key
    required: false
    default: ''
  r2-endpoint:
    description: Cloudflare R2 S3-compatible endpoint
    required: false
    default: ''
  r2-bucket:
    description: R2 bucket name for BuildStream cache
    required: false
    default: bst-cache
  bst2-image:
    description: BuildStream 2 container image reference
    required: true

runs:
  using: composite
  steps:
    - name: Free disk space
      uses: ublue-os/remove-unwanted-software@695eb75bc387dbcd9685a8e72d23439d8686cba6

    - name: Pull BuildStream container image
      shell: bash
      run: podman pull "${{ inputs.bst2-image }}"

    - name: Cache BuildStream sources
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ~/.cache/buildstream/sources
        key: bst-sources-${{ hashFiles('elements/**/*.bst', 'project.conf') }}
        restore-keys: |
          bst-sources-

    - name: Prepare BuildStream cache directory
      shell: bash
      run: |
        mkdir -p "$HOME/.cache/buildstream/sources"
        mkdir -p "$HOME/.cache/buildstream/cas"
        mkdir -p "$HOME/.cache/buildstream/artifacts"
        mkdir -p "$HOME/.cache/buildstream/source_protos"

    - name: Install rclone
      shell: bash
      run: |
        curl -fsSL https://rclone.org/install.sh | sudo bash
        rclone version

    - name: Restore BuildStream cache from R2
      shell: bash
      env:
        R2_ACCESS_KEY: ${{ inputs.r2-access-key }}
        R2_SECRET_KEY: ${{ inputs.r2-secret-key }}
        R2_ENDPOINT: ${{ inputs.r2-endpoint }}
        R2_BUCKET: ${{ inputs.r2-bucket }}
      run: |
        if [ -z "${R2_ACCESS_KEY}" ]; then
          echo "R2 secrets not configured, skipping cache restore"
          exit 0
        fi

        # Configure rclone for Cloudflare R2 (S3-compatible)
        mkdir -p ~/.config/rclone
        cat > ~/.config/rclone/rclone.conf <<EOF
        [r2]
        type = s3
        provider = Cloudflare
        access_key_id = $R2_ACCESS_KEY
        secret_access_key = $R2_SECRET_KEY
        endpoint = $R2_ENDPOINT
        no_check_bucket = true
        EOF
        # Strip leading whitespace from config (heredoc is indented in YAML)
        sed -i 's/^[[:space:]]*//' ~/.config/rclone/rclone.conf

        BST_CACHE="$HOME/.cache/buildstream"

        echo "=== Restoring CAS objects from R2 ==="
        rclone sync "r2:${R2_BUCKET}/cas/" "${BST_CACHE}/cas/" \
          --transfers=32 \
          --checkers=64 \
          --fast-list \
          --stats=10s \
          --stats-one-line \
          -v || echo "::warning::CAS restore from R2 failed (non-fatal)"

        echo "=== Restoring artifact refs from R2 ==="
        rclone sync "r2:${R2_BUCKET}/artifacts/" "${BST_CACHE}/artifacts/" \
          --transfers=16 \
          --checkers=32 \
          --fast-list \
          -v || echo "::warning::Artifact refs restore from R2 failed (non-fatal)"

        echo "=== Restoring source protos from R2 ==="
        rclone sync "r2:${R2_BUCKET}/source_protos/" "${BST_CACHE}/source_protos/" \
          --transfers=16 \
          --checkers=32 \
          --fast-list \
          -v || echo "::warning::Source protos restore from R2 failed (non-fatal)"

        echo "=== Cache restore summary ==="
        du -sh "${BST_CACHE}/cas" "${BST_CACHE}/artifacts" \
               "${BST_CACHE}/source_protos" "${BST_CACHE}/sources" 2>/dev/null || true
        df -h /

    - name: Disk space before build
      shell: bash
      run: df -h /

    - name: Generate BuildStream CI config
      shell: bash
      run: |
        mkdir -p logs
        cat > buildstream-ci.conf <<'BSTCONF'
        scheduler:
          on-error: continue
          fetchers: 12
          builders: 1
          network-retries: 3

        logging:
          message-format: '[%{wallclock}][%{elapsed}][%{key}][%{element}] %{action} %{message}'
          error-lines: 80

        build:
          max-jobs: 0
          retry-failed: True

        cache:
          cache-buildtrees: never
        BSTCONF

        echo "=== BuildStream CI config ==="
        cat buildstream-ci.conf
